### ISSUE TITLE
Automatic Deployment When Working from WordPress iOS

### ISSUE THREAD

**Issue by sahandnayebaziz** [nfmohit-wpmudev/deploy-netlifypress#1]
Hello @nfmohit-wpmudev! Big fan of this plugin, it works wonderfully.

I currently use a couple of WordPress deployments that are mostly updated by authors using the [WordPress iOS app](https://apps.wordpress.com/mobile/). In my testing, it seems like publishing or updating a post from the mobile app  does not currently take any advantage of this plugin. 

I'm curious — I thought there were global sort-of WordPress "hooks" that can be listened to. If these global hooks exist, is this how this plugin works? Is using a "post-published" hook on the WordPress install, triggered by a publish from the app, anywhere in the realm of possibility?

**Comment by sahandnayebaziz** [comment]
I would love to contribute, but also I'm unsure if I am even thinking of WordPress' inner workings in the proper way.

**Comment by sahandnayebaziz** [comment]
Okay, I was just able to confirm that it is possible to trigger the hooks from the Wordpress iOS app, using [this other plugin](https://github.com/crgeary/wp-jamstack-deployments), updating a post from the app triggered a build on Netlify! I haven't looked into the code difference yet, but I'll look and try to make a contribution here with the added functionality in a PR.

**Comment by nfmohit-wpmudev** [comment]
Hi there @sahandnayebaziz ! 👋
I hope you are having a great day! ❤️

First of all, I apologize for the delayed response. I just got back from my own wedding and thus have got a huge backlog of work 😰

Thank you very much for using this plugin and for your kind words 🙇‍♂️

I'm sorry to hear about the issue that you encountered. The plugin does use the global WordPress hooks to trigger deployments, i.e. `save_post`. I haven't tested it yet with the mobile WordPress apps, but it not working with them is definitely unexpected.

Thank you for reporting this issue and for your interest in looking into and contributing to the plugin.

I'll now also take a look at it and test it with the WordPress mobile apps.

Thank you!

Regards,
Nahid

**Comment by sahandnayebaziz** [comment]
Hello! Thank you! Congratulations on your wedding :) 

I am sure you will be able to spot the difference and what is missing much faster than I could, so I'm looking forward to what you find. My guess is that is just a specific hook or two that is missing? I'm not sure. From what I read, `save_post` etc seem so central that I thought they would be running for sure even if triggered from the app. 

All the best,
Sahand

**Comment by nfmohit-wpmudev** [comment]
Hey @sahandnayebaziz ! 👋
I hope you are doing well today! ❤️

Thank you for your kind words. Could you please possibly give the [fix/deploy-from-mobile-apps](https://github.com/nfmohit-wpmudev/deploy-netlifypress/tree/fix/deploy-from-mobile-apps) branch a try and see if that works for you?

Before my action was fired with the `save_post` hook, I'm currently doing a user role check to make sure the current user is an admin. For some reason, that user check is failing on the mobile apps (I'm exactly not sure why as I don't have much knowledge about the WordPress mobile apps and the XML-RPC API).

Upon further considerations, I realized that the user role check is not really necessary as users without the admin role can also publish/edit posts (e.g. editor, author). As a result, I've removed the user role check in the above-mentioned branch and according to my tests, triggers from the mobile apps are now working.

I'd be grateful if you could test this branch once and let me know if this works for you.

Also, I’m very happy to hear that this plugin was useful to you, thank you for the kind words! I’d really appreciate it if you could [share your feedback regarding the plugin in the form of a review](https://wordpress.org/support/plugin/deploy-netlifypress/reviews/#new-post) so that it can help other users seeking a similar solution.

Thank you very much!

Kind regards,
Nahid

**Comment by sahandnayebaziz** [comment]
Hey @nfmohit-wpmudev ! I just tested it and it worked perfectly! 😍

That totally makes sense. 

I will absolutely share my feedback with a review. Thank you for the great support and the great plugin. 

By the way, I especially love the descriptive titles in the Netlify deploys. That is a great touch.

Best,
Sahand

**Comment by nfmohit-wpmudev** [comment]
Hey @sahandnayebaziz ! 

Thank you very much for testing this out for me. I've queued this for the next update as I've some more features planned to be released as well.

Just saw the review, thank you so very much for sharing the kind words!

Also, thank you for your feedback regarding the descriptive titles, I find them very helpful as well.

Asides, please let me know if you would like to see some more features, please let me know, thank you!

Kind regards,
Nahid
