### ISSUE TITLE
Syntax improvement - php files

### ISSUE THREAD

**Issue by NacimHarfouche** [nfmohit-wpmudev/deploy-netlifypress#4]
I can see in some files that you used :

`<?php echo "something"  ?>`

but you can use in this case directly :

`<?= "something"  ?>`

its a shortcut.

**Comment by nfmohit-wpmudev** [comment]
Hi, @NacimHarfouche !
I hope you are doing well today!

Thank you for your recommendation. I'm quite aware of this, but such shorthand definition is not acceptable to every standard. As this is a WordPress plugin, WordPress' PHP Coding Standards advises against this. You can read more [here](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#no-shorthand-php-tags).

Also, I'd consider something like this as more of a personal preference rather than an improvement.

Please let me know if you need any further assistance regarding this. Thanks!

Regards,
Nahid

**Comment by NacimHarfouche** [comment]
Yeah I did’t know that those was one of the specifications of Wordpress code writing.
I will read this.
Thx

**Comment by nfmohit-wpmudev** [comment]
Hi, @NacimHarfouche !

No problem. Sure.

For the mean time, I'll close this issue. Thanks!

Regards,
Nahid
